name: Publish @sql-preview/server
on:
  push:
    tags:
      - 'v*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build root and packages
        run: npm run build
        
      - name: Publish @sql-preview/server to NPM
        run: npm publish --access public
        working-directory: packages/sql-preview-server
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
